### ISSUE TITLE
Pack the drips parameters

### ISSUE THREAD

**Issue by CodeSandwich** [radicle-dev/drips-contracts#145]
# The current situation

Currently the `DripsReceiver` parameter is defined as:

```solidity
struct DripsReceiver {
    uint256 userId;
    uint128 amtPerSec;
    uint32 start;
    uint32 duration;
}
```

And `DripsReceiverSeen` event as:

```solidity
event DripsReceiverSeen(
    bytes32 indexed receiversHash,
    uint256 indexed userId,
    uint128 amtPerSec,
    uint32 start,
    uint32 duration
);
```

# The proposal

Pack all 3 of `amtPerSec`, `start` and `duration` into a single `uint256` word as

```
uint256 dripParams = amtPerSec << 64 | start << 32 | duration;
```

Technically we use a [User Defined Value Type](https://docs.soliditylang.org/en/latest/types.html#user-defined-value-types) for this.

## The advantages

- Lower events gas cost. Each emitted `DripsReceiverSeen` has gas usage reduced by 512, from 1893 to 1381

- Lower calldata gas cost. Each `DripsReceiver` in calldata has its maximum gas usage reduced by 256, from 1184 to 928. Additionally there's less to pass around in memory and hash. Bit-shifting is very cheap, so accessing fields is marginally more expensive.

- Easier sorting of the receivers list. Instead of having a 4-step comparison (`userId` => `amtPerSec` => `start` => `duration`) we have a 2-step (`userId` => `dripParams`).

## The disadvantages

- Harder to work with API, requires packing and unpacking parameters.

**Comment by CodeSandwich** [comment]
Hi @0fatih,
It's only true when putting a struct in storage. Both for calldata and events each field is padded to 32 bytes.

**Comment by 0fatih** [comment]
Oh, so because of EVM's implicit conversion, the gas getting high, right?

**Comment by CodeSandwich** [comment]
Yes, the ABI requires all numbers expanded to 32 bytes and the smart contract then validates it while parsing the calldata. The funny part is that it does not **convert** the numbers, the EVM is a 256-bit machine and all values on stack are actually 32 bytes, even `uint8`s and `bool`s. Solidity can pretend that these are smaller integers for type safety and safe math. But that's off-topic.

**Comment by 0fatih** [comment]
Thank you for your clear explanations!

**Comment by xmxanuel** [comment]
I like the proposal. It make sense. We will have to do some bit manipulation on chain but is cheaper then emitting the events.
However, comparing makes it way easier. Elegant trick.

We anyway will have a SDK, so that off-chain 3rd party user don't need to deal with the encoding.
