### ISSUE TITLE
Support low-decimals tokens

### ISSUE THREAD

**Issue by CodeSandwich** [radicle-dev/drips-contracts#159]
Some tokens have very few decimals and it impacts the precision of dripping. E.g. USDC has only 6 decimals which leads to the minimum possible dripping rate of 2.629743 USDC per month, which is very impractical.

One solution is what Llama pay does: force every token to have additional 20 decimals. For our codebase it's infeasible, because this will make amounts of tokens with an already high precision and high supply not fit in 128-bit integers.

**Comment by CodeSandwich** [comment]
Some notes leading to the solution:
- Splits don't mind low decimals count, they're fine working on full units no matter how valuable they are. Support for fractions would make the logic extremely annoying with rounding and dust issues. Also support for fractions requires more storage space, so gas cost would increase.
- Drips consist of 3 main areas where amounts show up: drips configuration, sender's balance and receiver's amtDeltas. Like in splits, support for fractions in balance and amtDeltas is extremely annoying and costly in terms of storage.
- Drips configuration can easily accept higher precision. The additional cost is negligible, we can enforce additional 18 decimals by extending the amtPerSec from uint128 to uint192. The configuration will still fit neatly in a single 32-byte word.
- The rounding problems now focus in a single place: calculation of full-unit amtDeltas for each cycle based on fractional amtPerSec. We can't just calculate the dripping end time like we do now, it'd be theoretically valid, but it wouldn't correctly answer the question of how much is being dripped on each cycle. E.g. I'm dripping from cycle 1 to cycle 4. Cycles 2 and 3 MUST be receiving exactly the same amounts or the whole idea of amtDeltas crumbles. What we CAN do is round the dripped amount down on each cycle boundary. Example:
```
cycleLength: 4
amtPerSec: 1.3
startTime: 2
balance: 13
cycle 1: 2 seconds of 1.3 = 2, balance left: 11
cycle 2: 4 seconds of 1.3 = 5, balance left: 6
cycle 3: 4 seconds of 1.3 = 5, balance left: 1
cycle 4: 1 second of 1.3 = 1, balance left: 0

AmtDeltas:
cycle 1: currCycle = +2, nextCycle = +3
cycle 4: currCycle = -4, nextCycle = -1
```
I think that it should be relatively straight forward to implement it in Drips AND to simulate off-chain :thinking:

**Comment by xmxanuel** [comment]
I think your proposal sound like the right direction.

I agree that we don't need it for `Splits`. It is also fine to round down because we need to round anyway because we can not pay fractions. 

I think `10^18` give us also enough space.

Just for confirmation if I would set `amtPerSec=10^18` it would mean `1 Dai` or `1 USDC` per second. Indepented of the actual token precision.

Only in the USDC case we need to cut off more before the payout.  Mhm, or would it be the same because we don't have the higher precisions in the deltas?

What about using higher precisions for deltas? It would be to much cost changing the `uint128` correct?

**Comment by CodeSandwich** [comment]
> would it be the same because we don't have the higher precisions in the deltas?

That's right, it'd be the same.

> It would be to much cost changing the uint128 correct?

It would double the cost of any operation on deltas. It'd be also unclear what to do with the remaining fractions. Should they be returned to the sender? Which one? Should they be kept track of and made available for the receiver at some point? But then the received amount would be hard to predict.
