### ISSUE TITLE
Add squeezing drips for the current cycle

### ISSUE THREAD

**Issue by CodeSandwich** [radicle-dev/drips-contracts#164]
We want to better support use cases when there are few large drips incoming. For cases like this waiting for a cycle to end in order to receive funds may be a large problem.

A potential workaround is to allow receiving drips from users individually without waiting for the cycle end. Below is a proposal for implementation of a system like this. We've looked at a few approaches and this one seems the simplest while still being useful.

## Implementation

Add to stored per-user drips state a mapping:
```solidity
struct DripsState {
    ...
    mapping(uint256 => Squeezable) squeezables; // The key is the dripping user's ID
}

struct Squeezable {
    uint32 fromTimestamp; // A timestamp from which funds can be squeezed using the current receivers list
    uint128 amt; // An additional amount squeezable for `fromTimestamp`'s cycle
}
```

### Setting drips

When drips between Alice and Bob are updated, a few additional operations are done:
```solidity
Squeezable storage squeezable = dripsStates[Bob].squeezables[Alice];
// New cycle, clear the old `amt`, it can't be squeezed
if(_cycleOf(squeezable.fromTimestamp) != _cycleOf(block.timestamp) squeezable.amt = 0;
// Calculate amount dripped in the current cycle according to the old configuration which hasn't been squeezed yet
uint32 start = max(squeezable.fromTimestamp, _cycleOf(block.timestamp) * cycleSecs);
squeezable.amt += (block.timestamp - start) * oldAmtPerSec; 
squeezable.fromTimestamp = block.timestamp;
```

This operation means an extra slot written to. On the first drips setup between Alice to Bob Alice will pay extra 22K gas, on consecutive 5K.

### Receiving

`receiveDrips` gets an extra argument:

```solidity
function receiveDrips(..., Squeezed[] memory squeeze) ...

struct Squeezed {
    uint256 userId;
    DripsReceiver[] memory receivers;
}
```

`squeeze` can be empty, then receiving is unchanged. If it isn't, for each squeezed user their receivers list is verified against their on-chain hash. Then the receivers list is searched for the receiving user and for each matching entry the dripped amount is calculated for time range 
```solidity
max(squeezable.fromTimestamp, _cycleOf(block.timestamp) * cycleSecs) => block.timestamp
```
These amounts are summed up and added to
```solidity
_cycleOf(squeezable.fromTimestamp) == _cycleOf(block.timestamp) ? squeezable.amt : 0;
```
That amount is considered received. To prevent double receiving, `amtDeltas` for the currently running cycle must be reduced by the squeezed amount. It's safe, because the squeezed amount is at most the amount dripped in the current cycle up to the current timestamp.

Finally,`squeezables` is cleaned up:
```solidity
squeezable.amt = 0;
squeezable.fromTimestamp = block.timestamp`;
```

**Comment by CodeSandwich** [comment]
The above solution should work, but it's quite complex and easy to introduce bugs with additional structures and the nontrivial `Squeezable` updating logic. The gas usage is quite high too, in the worst case `setDrips` requires writing to additional 100 never used slots, that's 2.2 M gas just in `SSTORE`s.

Here's an alternative solution which we've been considering and which IMO is much better. It reduces the overhead on the sender side almost to zero (constant 5K gas to update a single slot) and puts any potential gas burden of analyzing drips configurations on the squeezing side.

# Implementation

Each user gets 2 new storage variables:

```solidity
struct DripsState {
    ...
    bytes32 historyHash;
    mapping(uint256 => uint32) lastSqueezed; // Key is the sender user ID
}
```

## Setting drips

On each `setDrips` call `historyHash` is updated:

```solidity
historyHash = keccak256(abi.encode(historyHash, block.timestamp(), _hashDrips(newReceivers)));
```

## Squeezing

Each receiver can squeeze from sender over a period of time:

```
max(lastSqueezed[sender], _cycleOf(block.timestamp) * cycleSecs) => block.timestamp
```

A new function is added:

```solidity
function squeezeDrips(uint256 userId, uint256 assetId, uint256 senderId, bytes32 initialHistoryHash, HistoryEntry[] history) public returns (uint128 amt) {
    ...
}

struct HistoryEntry {
    uint32 updateTime;
    DripsReceiver[] receivers; // If empty, use `receiversHash`
    bytes32 receiversHash;
}
```

`squeezeDrips` can then take `initialHistoryHash`, iterate over `history` and for each entry calculate the new `historyHash`. If the final one matches the sender's `historyHash`, `history` can be trusted to contain valid drips configurations and update timestamps. If an entry has a non-empty `receivers`, use `_hashDrips` of it, otherwise use the entry's `receiversHash`.

`squeezeDrips` can then calculate how much can be squeezed using `receivers` lists from `history`. This amount must be subtracted from the user's `amtDeltas`. `lastSqueezed[sender]` must be updated to match the latest squeezed timestamp.

There's no requirement for `history` entries to describe the entire squeezable time period. It's up to the user to decide which historical configurations are worth squeezing, after all each of them costs gas. The only potential trap is that after squeezing the user can't squeeze any range from before `lastSqueezed[sender]`, in the worst case scenario some funds will be stuck until the end of the cycle. Other designs are possible, but this one is simple, cheap to operate and doesn't force the user to squeeze potentially hundreds of uninteresting drips configurations to get the interesting ones.

**Comment by gh0stwheel** [comment]
Wow nice work @CodeSandwich! Really efficient and powerful design. And like you said, a much much better set of resource cost tradeoffs than the previous design. Amazing.

**Comment by xmxanuel** [comment]
Hey @CodeSandwich, @gh0stwheel 

nice work. :+1:  I think it is very similar to the hash history linked list design, we already developed a few weeks ago.

However with some nice improvements.

The main difference, I can currently see:
- we allow the user to squeeze some parts of a drip, the full period is not required.
- you can only squeeze the history once up to this timestamp.
- you don't need to provide the full history only from the first squeeze update period until the current config
- for memorizing the collected amount by squeezing we just modify the deltas instead of storing it in a separate variable

One question for understanding. 

The potential squeeze time period would always be from lastCollect up to `block.timestamp` or only from the start of the current cycle up to the `block.timestamp`?

I think from a user perspective you ideally want to collect an individual drip from `lastCollect` up to `block.timestamp`.

In that case, each individual collected update time-period would result in a delta modification, correct?

Let's say a sender has 3 different amtPerSec periods for a receiver.
```
// different amtPerSec time periods
5 -- 7 -- 10 -- now
```
The corresponding deltas would look something like
```
// deltas
+5 -- +2 -- +3 -- now
```

So, if a receiver wants to collect the 5 amtPerSec period (until the change to 7). 

We would have to subtract -5 in the delta but add the plus 5 again to the 7 amtPerSec start. 

```
+0 -- +7 -- +3 -- now
```

However, this is still a simplification because we have the current and next cycle deltas.

If I understood correctly, collecting individual update time periods would result in extra delta update costs.

```solidity
struct DripsState {
    ...
    bytes32 historyHash;
    mapping(uint256 => uint32) lastSqueezed; // Key is the sender user ID
}
```
Just to verify. If Bobs drips to Alice. The `historyHash` would be in the dripsState of Bob but the `lastSqueezed` would be the dripState of Alice with the `key` of Bob?

**Comment by CodeSandwich** [comment]
> The potential squeeze time period would always be from lastCollect up to block.timestamp or only from the start of the current cycle up to the block.timestamp?

It's from the larger one of them. Squeezing always from `lastCollect` brings all the problems you brought up, it's significantly more complex. It's also questionably useful, because the already finished cycles can be just `received` from, only the current cycle contains funds in a limbo.

**Comment by xmxanuel** [comment]
Yes, only allowing squeezing the current cycle makes it easier and effectively update the delta storage once even for multiple updates period. 

> It's also questionably useful, because the already finished cycles can be just received from,

I agree here. We only need to be aware how we present it to the user. 

I think it would be easier to understand => I can batch collect from all users until the end of a cycle or I can collect them individually until the now.

Now, it would be I can batch collect from all users until the end of a cycle and I can collect individually only for the current cycle. 

Maybe the other option would be nicer but it has too much technical complexity.

I think it is okay.
