### ISSUE TITLE
Squeezing can be vandalized

### ISSUE THREAD

**Issue by CodeSandwich** [radicle-dev/drips-contracts#202]
As of now anybody can squeeze for anybody else and there's nothing stopping a malicious user from squeezing using a history containing only the latest configuration. If there are more than one history entries which can be squeezed, that can lead to making funds unsqueezeable and locked until the cycle ends.

Some solutions:
- Ban squeezing for 3rd parties altogether. This reduces the robustness of the ecosystem.
- Implement ACL of who can squeeze. It's complicated and requires involvement.
- Ban skipping history entries except the latest ones. This forces everybody to cover the cost of squeezing the entire history for the current cycle whether it makes a financial sense or not.
- Same as above, but not for the squeezed user themselves. This bans malicious actions, but still reduces the efficiency of squeezing. It also increases the API complexity.
- Keep track of which configurations have been squeezed in the current cycle. It may be enough to store a bit map with flags. It greatly increases flexibility without making the usage much more complex, but it may be technically challenging.

**Comment by gh0stwheel** [comment]
Great writeup of this subtle issue @CodeSandwich!

I would suggest that we ban squeezing for 3rd parties altogether (the solution in your first bullet), since it's the most straightforward solution to meet the need and given that I don't think we have visibility into clear-cut cases where 3rd parties would need to squeeze for a user.

**Comment by CodeSandwich** [comment]
I've looked into it and I agree, for now let's just restrict squeezing to 1st party.

**Comment by CodeSandwich** [comment]
When we have more time in the future we may try to tackle solution 5, it's quite complex, but doable in a cheap to operate way. Here are some rough notes, I don't want to spend too much time writing it down, it's just a reminder of an idea.

We can store on-chain per sender-receiver pair a structure like this:
```solidity
struct {
    uint32[] nextSqueezed;
    uint16 statesLen;
    bool[] states;
}
```

The lower 240 bits of `statesLen` is occupied by the first 240 elements of `states`, if there are more elements, store them in the slots following. This trick reduces storage access if there aren't too many `states`. We can use OpenZeppelin's `BitMap` structure.

A new requirement is enforced: when squeezing, the whole history of the current cycle must be passed, even if it starts with many non-squeezed entries.

`states` contains pairs of bits, the first bit flags if the entry has been fully squeezed. The seconds bit flags if it has been squeezed partially. When squeezing a history entry, see its index in the current cycle history and check if it has been fully squeezed, if so, skip it. If it has been only partially squeezed, look up `nextSqueezed` for that index and see from which timestamp squeezing can be done. After squeezing update the `states` to reflect the new state. If the history has been expanded, increase `nextSqueezed` to reflect that. If the currently active drips configuration has been squeezed, set `nextSqueezed` for that configuration index to the current timestamp. If a new cycle has been started, reset `statesLen` to 0 and consider `states` empty.

This solution limits number of writes to at most 1 slot in `nextSqueezed` and `(historyLen + 136) / 128` slots in `statesLen / states`, which is usually just 1 slot.

To signal what has been squeezed and what can be squeezed the `SqueezedDrips` event needs to contain a bitmap of which historical configurations have been squeezed. This should be enough to tell off-chain which ones are fully squeezed, which partially, and what these configurations are.
