### ISSUE TITLE
Add squeezed history entries to `SqueezedDrips` event

### ISSUE THREAD

**Issue by CodeSandwich** [radicle-dev/drips-contracts#242]
There's no way to tell from the events which drips history entries have been squeezed. This is an important information, because without it it's unclear which entries can still be squeezed and which are exhausted.

## Solution

Extend
```solidity
event SqueezedDrips(
    uint256 indexed userId, uint256 indexed assetId, uint256 indexed senderId, uint128 amt
);
```
with `bytes32[] dripsHistoryHashes` into
```solidity
event SqueezedDrips(
    uint256 indexed userId, uint256 indexed assetId, uint256 indexed senderId, uint128 amt, bytes32[] dripsHistoryHashes
);
```
`dripsHistoryHashes` should contain all the successfully squeezed drips configurations' history hashes. These hashes can be then used to filter the sender's `DripsSet` events with matching `dripsHistoryHash`es to see what was squeezed.

There are 2 drawbacks:
- `DripsSet` can't have `dripsHistoryHash` indexed, because there are already 3 indexed fields. These events can't be filtered perfectly, all one can do is query for `DripsSet` with the squeezed sender's `userId` and `assetId`, the rest of filtering must be done locally. Alternatively subgraph can be used.
- `dripsHistoryHashes` will increase the cost of squeezing drips by 256 gas plus 256 per each squeezed drips configuration. Not a big problem.

**Comment by gh0stwheel** [comment]
This seems worthwhile to include in V2
