### ISSUE TITLE
Migrating to forge

### ISSUE THREAD

**Issue by ghost** [radicle-dev/drips-contracts#81]
[Foundry](https://github.com/gakonst/foundry), especially [forge](https://github.com/gakonst/foundry/tree/master/forge) provides helpful cheat-codes that can be utilized for more detailed testing.
Examples would be `expectRevert()` and `expectEmit()` for custom error and event tests.

In case I can convince you to migrate, I would be open to push a pr.

**Comment by CodeSandwich** [comment]
I'm eagerly awaiting Foundry, it's an awesome toolkit and I want to switch to it. Like you said, it allows testing events, which we needed to cut out when migrating from Hardhat and it's also MUCH faster. As of now I'd wait for it to stabilize a bit, at least until an official release. The switch isn't a burning issue, dapp-tools works fine enough, but it's reliable and battle tested.

**Comment by xmxanuel** [comment]
potential template https://github.com/FrankieIsLost/forge-template
