### ISSUE TITLE
Add a Gnosis Safe Manifest so it's easier to claim from a Safe recipient

### ISSUE THREAD

**Issue by GriffGreen** [radicle-dev/drips-contracts#88]
<img width="488" alt="Screen Shot 2022-01-31 at 4 33 10 PM" src="https://user-images.githubusercontent.com/14945613/151884662-16a50f45-41fa-4f69-b821-82d410283897.png">

I assume a lot of projects will have a Safe so it wont be just me trying to play :-D

Also bonus points if you make it an App and score some free advertising on there site
![Screen Shot 2022-01-31 at 4 39 15 PM](https://user-images.githubusercontent.com/14945613/151884846-a7e35d93-2662-4267-a111-b7d5b5dcfee7.png)

**Comment by CodeSandwich** [comment]
It's an important feature, but IIUC it requires work in the app, could you move this issue [to the app repo](https://github.com/radicle-dev/drips-app)?

**Comment by gh0stwheel** [comment]
You may be aware, but just in case, I wanted to share that the experience of using a Gnosis Safe with Drips via WalletConnect is a fairly decent user experience today:

https://docs.drips.network/docs/using-drips/using-a-gnosis-safe-with-drips

**Comment by CodeSandwich** [comment]
Resolved in the app.
